name: device_info_plugin_monorepo
repository: https://github.com/Thixq/device_info_plugin.git
version: 0.0.1
description: A plugin to get device information in Flutter.

environment: 
  sdk: ^3.11.5

workspace:
  - device_info_plugin/
  - device_info_plugin_ios/

dev_dependencies:
  melos: ^7.8.2

melos:
  ide:
    intellij:
      false
  sdkPath: .fvm/flutter_sdk
  version:
    linktoCommit: true
    workspaceChanelog: true
    changelogCommitBodies:
      include: true
  command:
    bootstrap:
      runPubGetInParallel: true
      hooks:
        post: |
          melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"

