name: device_info_plugin_ios
description: A starting point for Dart libraries or applications.
version: 0.0.4+1
repository: https://github.com/Thixq/device_info_plugin/tree/main/device_info_plugin_ios

environment:
  sdk: ^3.11.5
resolution: workspace

dependencies:
  device_info_plugin_platform_interface: ^0.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter
  mockito: ^5.6.4
  pigeon: ^27.1.0
  very_good_analysis: ^10.2.0

flutter:
  plugin:
    implements: device_info_plugin
    platforms:
      ios:
        dartPluginClass: DeviceInfoPluginPlugin
        pluginClass: DeviceInfoPluginPlugin
