// Mocks generated by Mockito 5.4.6 from annotations
// in device_info_plugin_android/test/device_info_plugin_android_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:device_info_plugin_android/src/messages.g.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceInfoAndroid_0 extends _i1.SmartFake
    implements _i2.DeviceInfoAndroid {
  _FakeDeviceInfoAndroid_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeviceInfoHostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoHostApi extends _i1.Mock implements _i2.DeviceInfoHostApi {
  @override
  String get pigeonVar_messageChannelSuffix =>
      (super.noSuchMethod(
            Invocation.getter(#pigeonVar_messageChannelSuffix),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#pigeonVar_messageChannelSuffix),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.DeviceInfoAndroid> getDeviceInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceInfo, []),
            returnValue: _i4.Future<_i2.DeviceInfoAndroid>.value(
              _FakeDeviceInfoAndroid_0(
                this,
                Invocation.method(#getDeviceInfo, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.DeviceInfoAndroid>.value(
              _FakeDeviceInfoAndroid_0(
                this,
                Invocation.method(#getDeviceInfo, []),
              ),
            ),
          )
          as _i4.Future<_i2.DeviceInfoAndroid>);
}
